# From https://github.com/sebastianbergmann/phpunit/blob/20ab19d3aed56fccf9569cd33c6cd0baab0ec272/.github/workflows/ci.yml
# (With many modifications)
name: Build Phar on Pull Request CI
on:
  pull_request:
    branches:
      - main
jobs:
  checkout_build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    name: Checkout & build Phar
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save repo content as artifact
        uses: actions/upload-artifact@v2
        with:
          name: full-workspace
          path: ${{ github.workspace }}
      - name: Full Composer Install
        run: composer install
      - name: Validate Code
        run: composer code:lint
      - name: Phar Build
        run: composer phar:build
      - name: permissions
        run: chmod +x ./robo
      - name: Save robo.phar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: robo-phar
          path: robo
          if-no-files-found: error
